"""Science provider — elements, units, formulas, planets, etc."""

from dataforge.providers.base import BaseProvider

_CHEMICAL_ELEMENTS: tuple[str, ...] = (
    "Hydrogen",
    "Helium",
    "Lithium",
    "Beryllium",
    "Boron",
    "Carbon",
    "Nitrogen",
    "Oxygen",
    "Fluorine",
    "Neon",
    "Sodium",
    "Magnesium",
    "Aluminum",
    "Silicon",
    "Phosphorus",
    "Sulfur",
    "Chlorine",
    "Argon",
    "Potassium",
    "Calcium",
    "Scandium",
    "Titanium",
    "Vanadium",
    "Chromium",
    "Manganese",
    "Iron",
    "Cobalt",
    "Nickel",
    "Copper",
    "Zinc",
)

_ELEMENT_SYMBOLS: tuple[str, ...] = (
    "H",
    "He",
    "Li",
    "Be",
    "B",
    "C",
    "N",
    "O",
    "F",
    "Ne",
    "Na",
    "Mg",
    "Al",
    "Si",
    "P",
    "S",
    "Cl",
    "Ar",
    "K",
    "Ca",
    "Sc",
    "Ti",
    "V",
    "Cr",
    "Mn",
    "Fe",
    "Co",
    "Ni",
    "Cu",
    "Zn",
)

_SI_UNITS: tuple[str, ...] = (
    "meter (m)",
    "kilogram (kg)",
    "second (s)",
    "ampere (A)",
    "kelvin (K)",
    "mole (mol)",
    "candela (cd)",
    "hertz (Hz)",
    "newton (N)",
    "pascal (Pa)",
    "joule (J)",
    "watt (W)",
    "coulomb (C)",
    "volt (V)",
    "farad (F)",
    "ohm (Ω)",
    "siemens (S)",
    "weber (Wb)",
    "tesla (T)",
    "henry (H)",
    "lumen (lm)",
    "lux (lx)",
    "becquerel (Bq)",
    "gray (Gy)",
    "sievert (Sv)",
)

_PLANETS: tuple[str, ...] = (
    "Mercury",
    "Venus",
    "Earth",
    "Mars",
    "Jupiter",
    "Saturn",
    "Uranus",
    "Neptune",
)

_GALAXIES: tuple[str, ...] = (
    "Milky Way",
    "Andromeda",
    "Triangulum",
    "Centaurus A",
    "Messier 87",
    "Sombrero Galaxy",
    "Whirlpool Galaxy",
    "Pinwheel Galaxy",
    "Cartwheel Galaxy",
    "Cigar Galaxy",
    "Black Eye Galaxy",
    "Sunflower Galaxy",
    "Tadpole Galaxy",
    "Hoag's Object",
    "NGC 1300",
)

_CONSTELLATIONS: tuple[str, ...] = (
    "Orion",
    "Ursa Major",
    "Ursa Minor",
    "Cassiopeia",
    "Scorpius",
    "Leo",
    "Gemini",
    "Taurus",
    "Sagittarius",
    "Andromeda",
    "Aquarius",
    "Aries",
    "Cancer",
    "Capricornus",
    "Libra",
)

_SCIENTIFIC_DISCIPLINES: tuple[str, ...] = (
    "Physics",
    "Chemistry",
    "Biology",
    "Mathematics",
    "Astronomy",
    "Geology",
    "Ecology",
    "Genetics",
    "Neuroscience",
    "Biochemistry",
    "Quantum Mechanics",
    "Thermodynamics",
    "Electrodynamics",
    "Organic Chemistry",
    "Inorganic Chemistry",
)

_METRIC_PREFIXES: tuple[str, ...] = (
    "yotta (Y)",
    "zetta (Z)",
    "exa (E)",
    "peta (P)",
    "tera (T)",
    "giga (G)",
    "mega (M)",
    "kilo (k)",
    "hecto (h)",
    "deca (da)",
    "deci (d)",
    "centi (c)",
    "milli (m)",
    "micro (μ)",
    "nano (n)",
    "pico (p)",
    "femto (f)",
    "atto (a)",
)


class ScienceProvider(BaseProvider):
    """Generates fake science data — elements, planets, units, etc."""

    __slots__ = ()

    _provider_name = "science"
    _locale_modules: tuple[str, ...] = ()
    _field_map: dict[str, str] = {
        "chemical_element": "chemical_element",
        "element": "chemical_element",
        "element_symbol": "element_symbol",
        "si_unit": "si_unit",
        "unit": "si_unit",
        "planet": "planet",
        "galaxy": "galaxy",
        "constellation": "constellation",
        "scientific_discipline": "scientific_discipline",
        "discipline": "scientific_discipline",
        "metric_prefix": "metric_prefix",
    }

    _choice_fields: dict[str, tuple[str, ...]] = {
        "chemical_element": _CHEMICAL_ELEMENTS,
        "element_symbol": _ELEMENT_SYMBOLS,
        "si_unit": _SI_UNITS,
        "planet": _PLANETS,
        "galaxy": _GALAXIES,
        "constellation": _CONSTELLATIONS,
        "scientific_discipline": _SCIENTIFIC_DISCIPLINES,
        "metric_prefix": _METRIC_PREFIXES,
    }
